let ast = { type: 1,
  tag: 'div',
  attrsList: [ [length]: 0 ],
  attrsMap: { class: 'login' },
  rawAttrsMap: {},
  parent: undefined,
  children:
   [ { type: 1,
       tag: 'LoginTab',
       attrsList: [ [length]: 0 ],
       attrsMap: { ref: 'loginTab' },
       rawAttrsMap: {},
       parent: [Circular],
       children: [ [length]: 0 ],
       plain: false,
       ref: '"loginTab"',
       refInFor: false,
       static: false,
       staticRoot: false,
       pre: undefined },
     { type: 3, text: ' ', static: true },
     { type: 1,
       tag: 'LoginByAcount',
       attrsList:
        [ { name: ':allDisabled', value: 'allDisabled' }, [length]: 1 ],
       attrsMap: { ref: 'loginByAcount', ':allDisabled': 'allDisabled' },
       rawAttrsMap: {},
       parent: [Circular],
       children: [ [length]: 0 ],
       plain: false,
       ref: '"loginByAcount"',
       refInFor: false,
       hasBindings: true,
       attrs:
        [ { name: 'allDisabled', value: 'allDisabled', dynamic: false },
          [length]: 1 ],
       static: false,
       staticRoot: false,
       pre: undefined },
     { type: 3, text: ' ', static: true },
     { type: 1,
       tag: 'div',
       attrsList: [ [length]: 0 ],
       attrsMap: { class: 'other-opr' },
       rawAttrsMap: {},
       parent: [Circular],
       children:
        [ { type: 2,
            expression: '_s(_f("filter2")(_f("filter1")(otherVar)))',
            tokens: [Array],
            text: '{{ otherVar | filter1 | filter2 }}',
            static: false },
          [length]: 1 ],
       plain: false,
       staticClass: '"other-opr"',
       static: false,
       staticRoot: false,
       pre: undefined },
     [length]: 5 ],
  plain: false,
  staticClass: '"login"',
  static: false,
  staticRoot: false }